/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'SacredSite' : null } |
  { 'NatureAdventure' : null } |
  { 'HeritageArchitecture' : null } |
  { 'AncientShrine' : null };
export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Destination {
  'id' : bigint,
  'tagline' : string,
  'name' : string,
  'description' : string,
  'category' : Category,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllDestinations' : ActorMethod<[], Array<Destination>>,
  'getAllSubscribers' : ActorMethod<[], Array<string>>,
  'getDestinationById' : ActorMethod<[bigint], Destination>,
  'initialize' : ActorMethod<[], undefined>,
  'submitContactMessage' : ActorMethod<[string, string, string], undefined>,
  'subscribeNewsletter' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];