/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Category = IDL.Variant({
  'SacredSite' : IDL.Null,
  'NatureAdventure' : IDL.Null,
  'HeritageArchitecture' : IDL.Null,
  'AncientShrine' : IDL.Null,
});
export const Destination = IDL.Record({
  'id' : IDL.Nat,
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
});

export const idlService = IDL.Service({
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  'getAllSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getDestinationById' : IDL.Func([IDL.Nat], [Destination], ['query']),
  'initialize' : IDL.Func([], [], []),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Category = IDL.Variant({
    'SacredSite' : IDL.Null,
    'NatureAdventure' : IDL.Null,
    'HeritageArchitecture' : IDL.Null,
    'AncientShrine' : IDL.Null,
  });
  const Destination = IDL.Record({
    'id' : IDL.Nat,
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
  });
  
  return IDL.Service({
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
    'getAllSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getDestinationById' : IDL.Func([IDL.Nat], [Destination], ['query']),
    'initialize' : IDL.Func([], [], []),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };